version: "3.7"

x-db-env: &db-env
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

x-api-env: &api-env
  <<: *db-env
  DEVELOPMENT: "true"
  DEBUG: ${DEBUG}
  ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  SECRET_KEY: ${SECRET_KEY}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}

services:
  api:
    build: .
    image: api-dev
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    restart: always
    environment: *api-env
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: *db-env
    restart: always
    ports:
      - 5433:5433

volumes:
  postgres_data:
  postgres_test_data:
